export const SIM = {
  canvas: "sim-canvas",
  topBar: "top-bar",
  resetBtn: "reset-btn",
  pauseBtn: "pause-btn",
  followCamBtn: "follow-cam-btn",
  topCamBtn: "top-cam-btn",
  orbitCamBtn: "orbit-cam-btn",
  // Left sidebar
  leftSidebar: "left-sidebar",
  airaProfile: "aira-profile",
  goalSelect: "goal-select",
  goalAssignBtn: "goal-assign-btn",
  spawnBox: "spawn-box-btn",
  spawnRamp: "spawn-ramp-btn",
  spawnBall: "spawn-ball-btn",
  spawnTarget: "spawn-target-btn",
  spawnLight: "spawn-light-btn",
  spawnLiftBox: "spawn-liftbox-btn",
  clearObjectsBtn: "clear-objects-btn",
  // Right sidebar
  rightSidebar: "right-sidebar",
  telPosition: "tel-position",
  telVelocity: "tel-velocity",
  telState: "tel-state",
  telGoal: "tel-goal",
  telDistance: "tel-distance",
  telAttempts: "tel-attempts",
  telSuccesses: "tel-successes",
  telFalls: "tel-falls",
  speedSlider: "speed-slider",
  balanceSlider: "balance-slider",
  jumpSlider: "jump-slider",
  saveBtn: "save-btn",
  loadBtn: "load-btn",
};
